#ifndef ASO_GPU_CONFIG_H
#define ASO_GPU_CONFIG_H

#define ASO_VK_VALIDATION_LAYER_COUNT 1
#define ASO_VK_DEVICE_EXTENSION_COUNT 1
#define ASO_VK_SWAP_CHAIN_MAX_IMAGES  4
#define ASO_VK_MAX_SURFACE_FORMATS    32
#define ASO_VK_MAX_PRESENT_MODES      8
#define ASO_VK_FRAMES_IN_FLIGHT       2

#endif // ASO_GPU_CONFIG_H
